name: Run tests with maven on main branch on every push

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Set JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: nc_report.log
